/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The registry provider info contains the base info and capability declarations of the registry provider
type RegistryProviderInfo struct {
	// The endpoint pattern
	EndpointPattern *RegistryProviderEndpointPattern `json:"endpoint_pattern,omitempty"`
	// The credential pattern
	CredentialPattern *RegistryProviderCredentialPattern `json:"credential_pattern,omitempty"`
}
