/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// worker in the pool
type Worker struct {
	// The checkin time of the worker
	CheckinAt time.Time `json:"checkin_at,omitempty"`
	// the checkin of the running job in the worker
	CheckIn string `json:"check_in,omitempty"`
	// The start time of the worker
	StartAt time.Time `json:"start_at,omitempty"`
	// the id of the running job in the worker
	JobId string `json:"job_id,omitempty"`
	// the id of the worker
	Id string `json:"id,omitempty"`
	// the id of the worker pool
	PoolId string `json:"pool_id,omitempty"`
	// the name of the running job in the worker
	JobName string `json:"job_name,omitempty"`
}
