/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ImmutableRule struct {
	Priority       int32                          `json:"priority,omitempty"`
	ScopeSelectors map[string][]ImmutableSelector `json:"scope_selectors,omitempty"`
	Disabled       bool                           `json:"disabled,omitempty"`
	Params         map[string]interface{}         `json:"params,omitempty"`
	Template       string                         `json:"template,omitempty"`
	Action         string                         `json:"action,omitempty"`
	TagSelectors   []ImmutableSelector            `json:"tag_selectors,omitempty"`
	Id             int32                          `json:"id,omitempty"`
}
