/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Storage struct {
	// Total volume size.
	Total int32 `json:"total,omitempty"`
	// Free volume size.
	Free int32 `json:"free,omitempty"`
}
