/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LdapUser struct {
	// ldap username.
	Username string `json:"username,omitempty"`
	// The user realname from \"uid\" or \"cn\" attribute.
	Realname string `json:"realname,omitempty"`
	// The user email address from \"mail\" or \"email\" attribute.
	Email string `json:"email,omitempty"`
}
