/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The registry endpoint pattern
type RegistryProviderEndpointPattern struct {
	// The endpoint list
	Endpoints []RegistryEndpoint `json:"endpoints,omitempty"`
	// The endpoint type
	EndpointType string `json:"endpoint_type,omitempty"`
}
