/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RetentionExecutionTask struct {
	Status         string `json:"status,omitempty"`
	Retained       int32  `json:"retained,omitempty"`
	JobId          string `json:"job_id,omitempty"`
	Repository     string `json:"repository,omitempty"`
	StatusCode     int32  `json:"status_code,omitempty"`
	StartTime      string `json:"start_time,omitempty"`
	StatusRevision int64  `json:"status_revision,omitempty"`
	EndTime        string `json:"end_time,omitempty"`
	Total          int32  `json:"total,omitempty"`
	Id             int64  `json:"id,omitempty"`
	ExecutionId    int64  `json:"execution_id,omitempty"`
}
