/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// retention policy
type RetentionPolicy struct {
	Rules     []RetentionRule       `json:"rules,omitempty"`
	Scope     *RetentionPolicyScope `json:"scope,omitempty"`
	Trigger   *RetentionRuleTrigger `json:"trigger,omitempty"`
	Id        int64                 `json:"id,omitempty"`
	Algorithm string                `json:"algorithm,omitempty"`
}
