/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Supported webhook event types and notify types.
type SupportedWebhookEventTypes struct {
	PayloadFormats []PayloadFormat `json:"payload_formats,omitempty"`
	EventType      []EventType     `json:"event_type,omitempty"`
	NotifyType     []NotifyType    `json:"notify_type,omitempty"`
}
