/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// The replication execution
type ReplicationExecution struct {
	// The status of the execution
	Status string `json:"status,omitempty"`
	// The status text
	StatusText string `json:"status_text,omitempty"`
	// The trigger mode
	Trigger string `json:"trigger,omitempty"`
	// The start time
	StartTime time.Time `json:"start_time,omitempty"`
	// The count of failed executions
	Failed int32 `json:"failed,omitempty"`
	// The count of succeed executions
	Succeed int32 `json:"succeed,omitempty"`
	// The count of stopped executions
	Stopped int32 `json:"stopped,omitempty"`
	// The end time
	EndTime time.Time `json:"end_time,omitempty"`
	// The count of in_progress executions
	InProgress int32 `json:"in_progress,omitempty"`
	// The total count of all executions
	Total int32 `json:"total,omitempty"`
	// The ID of the execution
	Id int32 `json:"id,omitempty"`
	// The ID if the policy that the execution belongs to
	PolicyId int32 `json:"policy_id,omitempty"`
}
