/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// The replication execution
type ScanDataExportExecution struct {
	// The status of the execution
	Status string `json:"status,omitempty"`
	// Indicates whether the export artifact is present in registry
	FilePresent bool `json:"file_present,omitempty"`
	// The ID if the user triggering the export job
	UserId int32 `json:"user_id,omitempty"`
	// The start time
	StartTime time.Time `json:"start_time,omitempty"`
	// The trigger mode
	Trigger string `json:"trigger,omitempty"`
	// The end time
	EndTime time.Time `json:"end_time,omitempty"`
	// The status text
	StatusText string `json:"status_text,omitempty"`
	// The name of the user triggering the job
	UserName string `json:"user_name,omitempty"`
	// The ID of the execution
	Id int32 `json:"id,omitempty"`
}
