/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type OidcUserInfo struct {
	// The update time of the OIDC user info record.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// the concatenation of sub and issuer in the ID token
	Subiss string `json:"subiss,omitempty"`
	// the ID of the user
	UserId int32 `json:"user_id,omitempty"`
	// The creation time of the OIDC user info record.
	CreationTime time.Time `json:"creation_time,omitempty"`
	// the secret of the OIDC user that can be used for CLI to push/pull artifacts
	Secret string `json:"secret,omitempty"`
	// the ID of the OIDC info record
	Id int32 `json:"id,omitempty"`
}
