/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PasswordReq struct {
	// New password for marking as to be updated.
	NewPassword string `json:"new_password,omitempty"`
	// The user's existing password.
	OldPassword string `json:"old_password,omitempty"`
}
