/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The style of the resource filter
type RegistryEndpoint struct {
	// The endpoint key
	Key string `json:"key,omitempty"`
	// The endpoint value
	Value string `json:"value,omitempty"`
}
