/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Registry struct {
	// Health status of the registry.
	Status     string              `json:"status,omitempty"`
	Credential *RegistryCredential `json:"credential,omitempty"`
	// The update time of the policy.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// The registry name.
	Name string `json:"name,omitempty"`
	// The registry URL string.
	Url string `json:"url,omitempty"`
	// Whether or not the certificate will be verified when Harbor tries to access the server.
	Insecure bool `json:"insecure,omitempty"`
	// The create time of the policy.
	CreationTime time.Time `json:"creation_time,omitempty"`
	// Type of the registry, e.g. 'harbor'.
	Type_ string `json:"type,omitempty"`
	// The registry ID.
	Id int64 `json:"id,omitempty"`
	// Description of the registry.
	Description string `json:"description,omitempty"`
}
