/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ScannerCapability struct {
	ProducesMimeTypes []string `json:"produces_mime_types,omitempty"`
	ConsumesMimeTypes []string `json:"consumes_mime_types,omitempty"`
}
