/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// the job queue info
type JobQueue struct {
	// The count of jobs in the job queue
	Count int32 `json:"count,omitempty"`
	// The latency the job queue (seconds)
	Latency int32 `json:"latency,omitempty"`
	// The paused status of the job queue
	Paused bool `json:"paused,omitempty"`
	// The type of the job queue
	JobType string `json:"job_type,omitempty"`
}
