/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RobotPermission struct {
	Access []Access `json:"access,omitempty"`
	// The kind of the permission
	Kind string `json:"kind,omitempty"`
	// The namespace of the permission
	Namespace string `json:"namespace,omitempty"`
}
