/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The metadata associated with the scan data export job
type ScanDataExportJob struct {
	// The id of the scan data export job
	Id int64 `json:"id,omitempty"`
}
