/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Statistic struct {
	// The count of the total projects, only be seen by the system admin
	TotalProjectCount int64 `json:"total_project_count,omitempty"`
	// The count of the public projects
	PublicProjectCount int64 `json:"public_project_count,omitempty"`
	// The count of the private projects
	PrivateProjectCount int64 `json:"private_project_count,omitempty"`
	// The total storage consumption of blobs, only be seen by the system admin
	TotalStorageConsumption int64 `json:"total_storage_consumption,omitempty"`
	// The count of the public repositories
	PublicRepoCount int64 `json:"public_repo_count,omitempty"`
	// The count of the total repositories, only be seen by the system admin
	TotalRepoCount int64 `json:"total_repo_count,omitempty"`
	// The count of the private repositories
	PrivateRepoCount int64 `json:"private_repo_count,omitempty"`
}
